### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Lmendev** [mensonones/sakura-card-captor-api#2]
Hi bro,

I hope you are well, 

I report that the server is showing an error when accessing the project index. 

Is still active the project ? 

Good day! 🙂

https://sakura-card-captor-api.herokuapp.com/

![CaptureSakura](https://user-images.githubusercontent.com/2933342/107197850-bab08780-69f4-11eb-9f46-bbd762485c58.JPG)

**Comment by mensonones** [comment]
Hey, @Lmendev. Thanks for the feedback! The database service was down. Now it's active again :)

**Comment by Lmendev** [comment]
Yeah! the server works again, thank you!
